### ISSUE TITLE
umami report is no more working since Aug 25 (2.12.x => 2.13.x)

### ISSUE THREAD

**Issue by creharmony** [boly38/action-umami-report#58]
````
Run boly38/action-umami-report@umami-server-2.12
fetchUmamiServerApi
errTypeError: this.siteEvents.reduce is not a function
ERROR: TypeError: this.siteEvents.reduce is not a function
Error: TypeError: this.siteEvents.reduce is not a function
````

Aug 26 , Umami self-hosted version has been updated from `2.12.1` to `2.13.1`

**Comment by boly38** [comment]
- [umamiClient](https://github.com/boly38/umami-api-client).getEvents results is page

**Comment by boly38** [comment]
quick fix here has been to switch on websites/metrics [typpe=event] api (+ move `tz` query param to `timezone`)
